language: node_js
node_js:
  - "14" # Vous pouvez ajuster la version de Node.js selon vos besoins

# Mise en cache des dépendances pour accélérer les builds
cache:
  directories:
    - node_modules

# Installez les dépendances
install:
  - npm ci # Utilise 'npm ci' pour une installation plus rapide et fiable

# Exécutez les scripts de linting et de build
script:
  - npm run lint # Exécute ESLint pour vérifier le code
  - npm run build # Compile le projet avec Vite

# Notifications en cas d'échec de build
notifications:
  email:
    recipients:
      - votreadresse@example.com # Remplacez par votre adresse email
    on_success: never # Ne pas envoyer d'email en cas de succès
    on_failure: always # Envoyer un email en cas d'échec

# Déploiement conditionnel (exemple)
# deploy:
#   provider: script
#   script: bash deploy.sh
#   on:
#     branch: main
